SRCS += main.cpp
SRCS += Animal.cpp
SRCS += Cat.cpp
SRCS += Dog.cpp
SRCS += WrongAnimal.cpp
SRCS += WrongCat.cpp

DEPS +=	Animal.hpp
DEPS += Cat.hpp
DEPS += Dog.hpp
DEPS += WrongAnimal.hpp
DEPS += WrongCat.hpp

CC			=	c++

FLAGS		+=	-Wall
FLAGS		+=	-Wextra
FLAGS		+=	-Werror
FLAGS		+=	-std=c++98

NAME		=	Animals

PATH_OBJS	+= objs
OBJS		+= $(patsubst %.cpp, $(PATH_OBJS)/%.o, $(SRCS))

all		: $(NAME)

$(NAME)	: $(OBJS)
	$(CC) $(FLAGS) $^ -o $@

$(OBJS)	: $(PATH_OBJS)/%.o : %.cpp Makefile $(DEPS)
	mkdir -p $(PATH_OBJS)
	$(CC) $(FLAGS) -c $< -o $@ -I .

clean	:
	rm -rf $(PATH_OBJS)

fclean	:	clean
	rm -f $(NAME)

re		:	fclean all

.PHONY	: all clean fclean re
